### ISSUE TITLE
TestCases ability to run just one test case

### ISSUE THREAD

**Issue by depaolim** [django-request/django-request#113]
Add the ability to run just one or a group of test cases

`python runtests.py [testcase]`

Examples:

`python runtests.py`

`python runtests.py tests.test_managers`

`python runtests.py tests.test_managers.RequestManagerTest`

`python runtests.py tests.test_managers.RequestManagerTest.test_active_users_with_options`

I'm providing a PR...

**Comment by ZuluPro** [comment]
Hello @depaolim,
Can I suggest you to do like that: https://github.com/ZuluPro/pony-admin/blob/master/runtests.py

In this way, we'll be able to run any commands,
And more we'll be able to use test command for choose tests and why not nose or pytests integration

**Comment by depaolim** [comment]
good hint @ZuluPro , thanks!
my solution was intended just as the "minimum necessary for the goal"
