### ISSUE TITLE
User on_delete set null

### ISSUE THREAD

**Issue by stevelacey** [django-request/django-request#138]
Set null might be a better default – I wouldn't expect to lose request logs if a user is a deleted, I never expect to lose request logs without explicitly deleting request logs.

**Comment by kylef** [comment]
Hey @stevelacey, I certainly agree with you. I think this is a relic from the past, django-request predate that option in Django.

Would you be interested in creating a pull request adding the necessary changes?

**Comment by stevelacey** [comment]
@kylef sure, though I just noticed that this was explicitly set to cascade in https://github.com/django-request/django-request/commit/3dab5b6a368eaf5b508cb0b683a5078b64b9d307 – but never made it into a tagged version – also worth noting that the 0001_initial migration was altered to include it too

**Comment by felixxm** [comment]
We added `on_delete=models.CASCADE` for compatibility with the Django 2.0 where this attribute is required. `models.CASCADE` is default in Django, therefore this change hasn't changed anything in the `django-request` behavior. 

I agree that it's a good idea to change to the `models.SET_NULL`.
