### ISSUE TITLE
Migration missed (needs makemigrations)

### ISSUE THREAD

**Issue by yapper-git** [django-request/django-request#150]
I think you missed to run makemigrations.

With django 1.11, I got a warning.

makemigrations creates a migration for request :

```
$ python manage.py makemigrations
Migrations for 'request':
  venv/lib/python3.6/site-packages/request/migrations/0006_auto_20170802_1531.py
    - Alter field method on request
```

```
$ cat venv/lib/python3.6/site-packages/request/migrations/0006_auto_20170802_1531.py
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.CharField(default='GET', max_length=7, verbose_name='method'),
        ),
    ]
>>>

**Comment by SearchDream** [comment]
I also have this issue.

**Comment by felixxm** [comment]
@SearchDream Can you provide more details? on which version of `Django` and `django-request` did you encounter this issue?

**Comment by SearchDream** [comment]
@felixxm I am using Django==1.11.8 and django-request==1.5.4

**Comment by SearchDream** [comment]
@felixxm Following is the migration file content:

`# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.CharField(default='GET', max_length=7, verbose_name='method'),
        ),
    ]
`

**Comment by felixxm** [comment]
@SearchDream Thanks for details.
