### ISSUE TITLE
migrate error

### ISSUE THREAD

**Issue by peterchen16** [django-request/django-request#151]
says can't import migrations from django.db when trying to migrate

**Comment by peterchen16** [comment]
from django.db import models, migrations
ImportError: cannot import name migrations

**Comment by peterchen16** [comment]
why?

**Comment by felixxm** [comment]
Sorry, but is it related with django-request package?

**Comment by peterchen16** [comment]
yes, 
 from python2.7/site-packages/request/migrations/0001_initial.py

**Comment by peterchen16** [comment]
when I try to run python manage.py migrate request

**Comment by felixxm** [comment]
What version of `Django` and `django-request `are you using?

**Comment by peterchen16** [comment]
Django 1.6.4

django-request 1.5.1

**Comment by felixxm** [comment]
`migrate` appeared in `Django` 1.7, therefore you probably used `syncdb`. I created test project locally and everything worked perfectly:
```
$ python manage.py syncdb
Creating tables ...
Creating table django_admin_log
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_groups
Creating table auth_user_user_permissions
Creating table auth_user
Creating table django_content_type
Creating table django_session
Creating table request_request
```
