### ISSUE TITLE
Request model need makemigrations

### ISSUE THREAD

**Issue by Marpop** [django-request/django-request#193]
`  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.`

`  /usr/local/lib/python3.6/site-packages/request/migrations/0006_auto_20190822_1445.py
    - Alter field method on request`

**Comment by felixxm** [comment]
Duplicate of #150.

**Comment by Marpop** [comment]
Hey, I know about that issue, but I'm using newer django (2.2.x) and django-request (1.5.0) versions

**Comment by felixxm** [comment]
I've just released [django-request 1.5.5](https://pypi.org/project/django-request/1.5.5/) and cannot reproduce this issue anymore.
