### ISSUE TITLE
Clarify that the sites framework is not required, and does not support HTTPS

### ISSUE THREAD

**Issue by mikaraunio** [django-request/django-request#228]
I setup `django-request` according to the instructions in the README, and was surprised to see that most of the entries in the Top Referrers were URLs on my own site, even though I had setup the `sites` framework as instructed.

Looking at the code revealed this is because the site uses HTTPS, but the `sites` lookup hardcodes HTTP as the protocol in `settings.py` line 40. This is actually mentioned in the docs for `REQUEST_BASE_URL`, but requires some digging to find.

With the vast majority of sites now being HTTPS, I would suggest updating the installation documentation to instruct setting  `REQUEST_BASE_URL` as appropriate,  instead of configuring the sites framework. This would also remove the (small, but non-negligible) overhead of that framework.

My proposal would be to replace the last step of the install instructions in README.md and docs/index.txt as follows:

> Add `REQUEST_BASE_URL` to your settings with the base URL of your site (e.g. `https://www.my.site/`). This is used to calculate unique visitors and top referrers. This is not needed if you are using the `django.contrib.sites` framework, and do not use HTTPS.

Can submit a PR if the wording is acceptable.

**Comment by felixxm** [comment]
Thanks for the report, your suggestion sounds good. Maybe instead of:
> This is not needed if you are using the `django.contrib.sites` framework, and do not use HTTPS.

We could just say:

> `REQUEST_BASE_URL` defaults to ``'http://%s' % Site.objects.get_current().domain``.

**Comment by mikaraunio** [comment]
I agree, that sounds clear and concise.

**Comment by mikaraunio** [comment]
Submitted PR #229.
