### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by jwedel** [django-request/django-request#230]
I just upgraded to Django 4 and starting the integration tests already fails. 

This was caused by different issues:
- importing `url` method which has been removed in Django 4 and replaced by `from django.urls import re_path`
- An error stating: 
```
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'request.templatetags.request_admin': cannot import name 'quote' from 'django.utils.http' (.../venv/lib/python3.8/site-packages/django/utils/http.py)
``` 
`django.utils.http.quote` should be replaced by `urllib.parse.quote`

See https://docs.djangoproject.com/en/4.0/releases/3.1/#deprecated-features-3-1

**Comment by hramezani** [comment]
I can see the following two commits to make the package compatible with Django 4.0:
https://github.com/django-request/django-request/commit/d577fac7e96ae5d04e9254fe76279e6c895467a5
https://github.com/django-request/django-request/commit/34fdd25dbdab27cb5aa1c86bb22427c71d9f63da

With the new release, these problems will be fixed!

**Comment by jwedel** [comment]
@hramezani yes! That looks great. Looking forward to the next release. 👍

**Comment by felixxm** [comment]
I will try to release in the next week.

**Comment by felixxm** [comment]
[django-request 1.6.0](https://pypi.org/project/django-request/1.6.0/) is ready.
