### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [django-request/django-request#245]
Could you please consider to utilize unittest.mock?

https://github.com/django-request/django-request
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by felixxm** [comment]
@pgajdos Thanks for the suggestion :+1: Would you like to prepare a patch?

**Comment by pgajdos** [comment]
@felixxm , sorry I have missed your request. Thank you!
(https://build.opensuse.org/package/view_file/devel:languages:python:django/python-django-request/python-django-request-no-mock.patch)
