### ISSUE TITLE
purgerequests does not seem to work

### ISSUE THREAD

**Issue by venteto** [django-request/django-request#266]
I am using django-request==1.6.2 and every time I run a variation of `python manage.py purgerequests` the command responds with "There are no requests to delete" and does not delete anything. I have to use psql to manually truncate the request_request table.

**Comment by felixxm** [comment]
`purgerequests` works for me :shrug:
```
$ python manage.py purgerequests 0 hours
You have requested a database reset.
This will IRREVERSIBLY DESTROY any
requests created before 0 hours ago.
That is a total of 114 requests.
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: ....
```
Please provide a sample project that reproduces the issue.
