### ISSUE TITLE
Can we get a release 1.6.3 with the recent fixes?

### ISSUE THREAD

**Issue by JulianFeinauer** [django-request/django-request#269]
Hi all,
currently I'm having problems with using 1.6.2 due to the bug reported in #261 .
This was fixed in February but there is no release since then and I would really appreciate one : )

Thanks!
Julian

**Comment by felixxm** [comment]
Thanks for the reminder, I will try to issue a release in the next few days.

**Comment by felixxm** [comment]
Released https://pypi.org/project/django-request/1.6.3/.
