### ISSUE TITLE
REQUEST_VALID_METHOD_NAMES default is missing "patch" method

### ISSUE THREAD

**Issue by Lcrs123** [django-request/django-request#290]
Given that every single method other than "patch" is already defined by default on REQUEST_VALID_METHOD_NAMES, was this an oversight?

**Comment by kylef** [comment]
The default follows the methods defined in the HTTP specification, and not custom ones defined outside core HTTP specifications. https://www.rfc-editor.org/rfc/rfc9110.html#name-methods CONNECT is omitted as it is a proxy construct and unlikely to be used.

**Comment by felixxm** [comment]
Closing per [comment](https://github.com/django-request/django-request/issues/290#issuecomment-2322869012).
