### ISSUE TITLE
If USE_THOUSAND_SEPARATOR is True, URL must be unlocalized

### ISSUE THREAD

**Issue by tecnosegugio** [django-request/django-request#48]
If USE_THOUSAND_SEPARATOR in project settings.py is True, all URLs that contain a number > 1000 are localized adding a thousands separator.
This happens when the whole project need to be localized for different countries and the ID of a record is above 1000.

URL must be unlocalized using the template tag "unlocalize" (https://docs.djangoproject.com/en/1.6/topics/i18n/formatting/#unlocalize)

See for example the latestrequests.html template, line 15: the {{ request.path }} must be rewritten in {{ request.path|unlocalize }}.

**Comment by felixxm** [comment]
`request.path` is a string it won't be localized.
