### ISSUE TITLE
Static contex processor inclusion (missing in doc)

### ISSUE THREAD

**Issue by gidantribal** [django-request/django-request#53]
The context processor for serving static files 
<code>'django.core.context_processors.static'</code>

must be included, otherwise the graph 
<code>http://mydomain/admin/request/request/overview/</code>
won't be shown (as the static files of django-request won't be served properly):

![screenshot 2014-05-25 18 30 30](https://cloud.githubusercontent.com/assets/6584624/3077440/9fa58af0-e42a-11e3-9e50-678ad9783251.jpg)

There is no mention in the official doc about this, it would probably help to mention this for easing the installation...

**Comment by felixxm** [comment]
`django.core.context_processors.static` is not necessary any more.
