### ISSUE TITLE
Host field in overview

### ISSUE THREAD

**Issue by juree** [django-request/django-request#74]
I really missing host field inside overview. 
Since we have a web pages with several subdomains (each user profile have one), from current overview i can not see if someone goes to subdomain.example.com as first request (path will show "/").

Now i improvise, and watch further requests referral link. 

Locally i have basic implementation of this feature, need to add few things and it is ready for pull request if you are interested.

But i have one question since i never had pull req like that. 
I can't achieve that after update, the migrate will add new field. All i can do is drop whole table and create new one with migration, but this is terrible approach (for losing data). I've modified init migration file and create new migration file, but with no success. Any ideas how to properly create new field without dropping current table?

**Comment by felixxm** [comment]
You can use [makemigrations](https://docs.djangoproject.com/en/1.10/ref/django-admin/#django-admin-makemigrations).
